// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Burnable.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";

/// Web3 Renewables Energy
/// This is a Proof of Concept NFT representing Energy generated by a specific Solar System
/// This NFT URI points to IPFS data about watt hours of power generated over 30 days
/// And has estimates of avoided emissions based on the grid mix of the solar system
/// Any questions or interest in working together contact us on Web3Renewables.com

contract Web3RenewablesEnergy is ERC721, ERC721Burnable, AccessControl {
    constructor() ERC721("Web3RenewablesEnergy", "W3REe") {
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
    }

    function _baseURI() internal pure override returns (string memory) {
        return "https://bafybeifdy6tz7pg2ltqmkrcdsyqebonzttxq7esbo5bbvw4hol4drwlaju.ipfs.w3s.link/JuneEnergyGeneration-EmissionsAvoided.json";
    }

    // The following functions are overrides required by Solidity.

    function supportsInterface(bytes4 interfaceId)
        public
        view
        override(ERC721, AccessControl)
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }
}